name: polygon_map_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.10.0
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  geolocator: ^10.1.0
  syncfusion_flutter_datagrid: ^28.1.35
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  



